defaults:
  - override hydra/launcher: slurm

tags: ~

hydra:
  launcher:
    cpus_per_task: 2
    mem: 15G
    gres: gpu:1
    env_type: singularity
    singularity_img: /scratch/work/public/singularity/cuda11.6.124-cudnn8.4.0.27-devel-ubuntu20.04.4.sif
    singularity_overlay: /scratch/nhn234/singularity/lookahead.ext3
##### SUGGESTED HYDRA CONFIG ###########################
  sweep: 
    # subdir is built dynamically using the tags
    dir: ${oc.env:HOME}/slurm/${oc.select:hydra.launcher.date,${now:%Y-%m-%d}}/${hydra.job.name}
  run:
    # once we're running set tags from conf
    dir: ${hydra.sweep.dir}/${join:${tags}}
########################################################
      #partition: gpu
